### ISSUE TITLE
Pip Installation Cannot Find Package

### ISSUE THREAD

**Issue by PeterCat12** [fp12/pychallonge_async#3]
After installing with `pip install -e git+http://github.com/fp12/pychallonge_async#egg=pychallonge_async` and attempting to run my simple test suite (Django, docker-compose, python 3.5.2) I get an error reading `No module named 'challonge'`. I get a similar error if I try `import pychallonge_async`. I'm not sure if this is an issue with my docker container not properly downloading `pychallonge_async` or if their is something incorrect with the `setup.py`. 

I am not too familiar with how pip works but is there a reason why `pip install pychallonge_async` does not work?

EDIT: Seems like the package is not being installed into my container as it is missing from `pip list`. Odd as it is definitely in my requirements.txt. I do notice, however, that it appears as `-e git+http://github.com/fp12/pychallonge_async@c57bc2524fa0707aa05a80b69ed51ca0c416eb28#egg=pychallonge_async` which differs from other packages `requests==2.12.1` for instance. My dockerfile has the standard `RUN pip install -r requirements.txt`. I wonder if this is a caching issue with `docker-compose build` not recognizing it as a new package or something... 

EDIT 2: After manually installing `pychallonge_async` on my docker-container I am, unfortunately, still not able to locate any module named `challonge` or `pychallonge_async`

EDIT 3: Per this post: http://stackoverflow.com/questions/29905909/pip-install-e-packages-dont-appear-in-docker , packages isntalled with -e don't appear in docker. I changed my `RUN pip install -r requirements.txt` to `pip install -r requirements.txt --src /usr/local/src` which resolved the issue. Problem was not related to your repo at all, but with docker/pip. I learned something new today!

**Comment by fp12** [comment]
That's cool to know, thanks for posting the solution!
