### ISSUE TITLE
processing check-ins always throws ChallongeException Bad Request

### ISSUE THREAD

**Issue by krehera** [fp12/pychallonge_async#8]
I'm doing something like this:
```
 if tournament['state'] == "checking_in":
     await challonge.tournaments.process_check_ins(tournament['id'])
```

and still getting Bad Request. But I don't think I'm doing anything wrong. Please take a quick glance at my [terrible] code and see if this should work or not...

https://github.com/krehera/SFCJbot/blob/pairings/sfcjbot.py#L368

sorry, I'm pretty new to submitting GitHub issues so if you need any other info just ask and I'll do my best to get it for you. Thanks!

**Comment by fp12** [comment]
Hey, sorry for the late reply...
Unfortunately, check-ins are not well handled from the Challonge API side... :/
Sometimes they work, but most of the time they don't. We'll need more support from Challonge for this unfortunately.
Sorry...

**Comment by krehera** [comment]
very well. I have created an issue on the Challonge feature requests page [here.](http://feedback.challonge.com/forums/44455-feature-requests/suggestions/18713728-allow-check-ins-via-api)
